import type { Phase10FeatureFlags } from "../feature-flags/types.ts";
import type { TrustIntelligenceFeatureFlags } from "./types.ts";

export function getTrustIntelligenceFeatureFlags(flags: Phase10FeatureFlags): TrustIntelligenceFeatureFlags {
  return {
    TRUST_INTELLIGENCE_FOUNDATION_ENABLED: flags.TRUST_INTELLIGENCE_FOUNDATION_ENABLED,
    TRUST_SIGNAL_MODEL_ENABLED: flags.TRUST_SIGNAL_MODEL_ENABLED,
    CIRCUMVENTION_SIGNAL_MODEL_ENABLED: flags.CIRCUMVENTION_SIGNAL_MODEL_ENABLED,
    PROGRESSIVE_CONFIDENCE_SCORING_ENABLED: flags.PROGRESSIVE_CONFIDENCE_SCORING_ENABLED,
    TRUST_EVIDENCE_EXPLAINABILITY_ENABLED: flags.TRUST_EVIDENCE_EXPLAINABILITY_ENABLED,
    TRUST_GRAPH_FOUNDATION_ENABLED: flags.TRUST_GRAPH_FOUNDATION_ENABLED,
    CANDIDATE_RECOMMENDATION_ENGINE_ENABLED: flags.CANDIDATE_RECOMMENDATION_ENGINE_ENABLED,
    RISK_AGGREGATION_ENABLED: flags.RISK_AGGREGATION_ENABLED,
    HUMAN_REVIEW_OVERRIDE_ENABLED: flags.HUMAN_REVIEW_OVERRIDE_ENABLED,
  };
}

export function createAllEnabledTrustIntelligenceFlags(): TrustIntelligenceFeatureFlags {
  return {
    TRUST_INTELLIGENCE_FOUNDATION_ENABLED: true,
    TRUST_SIGNAL_MODEL_ENABLED: true,
    CIRCUMVENTION_SIGNAL_MODEL_ENABLED: true,
    PROGRESSIVE_CONFIDENCE_SCORING_ENABLED: true,
    TRUST_EVIDENCE_EXPLAINABILITY_ENABLED: true,
    TRUST_GRAPH_FOUNDATION_ENABLED: true,
    CANDIDATE_RECOMMENDATION_ENGINE_ENABLED: true,
    RISK_AGGREGATION_ENABLED: true,
    HUMAN_REVIEW_OVERRIDE_ENABLED: true,
  };
}
