import type { JobCategory, JobListing } from "../types";

export const mockJobCategories: JobCategory[] = [
  { id: "construction", icon: "hardHat", openPositions: 12 },
  { id: "engineering", icon: "compass", openPositions: 8 },
  { id: "healthcare", icon: "pulse", openPositions: 10 },
  { id: "hospitality", icon: "serviceBell", openPositions: 7 },
  { id: "logistics", icon: "shipment", openPositions: 9 },
  { id: "manufacturing", icon: "factory", openPositions: 6 },
  { id: "administration", icon: "briefcase", openPositions: 5 },
  { id: "technology", icon: "chip", openPositions: 4 },
];

export const mockJobListings: JobListing[] = [
  {
    id: "job-001",
    categoryId: "construction",
    titleKey: "items.siteSupervisor.title",
    summaryKey: "items.siteSupervisor.summary",
    locationCountry: "Tunisia",
    locationCity: "Sousse",
    locationType: "onSite",
    employmentType: "fullTime",
    experienceLevel: "senior",
    postedAt: "2026-07-01",
    featured: true,
    responsibilitiesKeys: [
      "items.siteSupervisor.responsibilities.0",
      "items.siteSupervisor.responsibilities.1",
      "items.siteSupervisor.responsibilities.2",
    ],
    requirementsKeys: [
      "items.siteSupervisor.requirements.0",
      "items.siteSupervisor.requirements.1",
      "items.siteSupervisor.requirements.2",
    ],
  },
  {
    id: "job-002",
    categoryId: "engineering",
    titleKey: "items.mechanicalEngineer.title",
    summaryKey: "items.mechanicalEngineer.summary",
    locationCountry: "Qatar",
    locationCity: "Doha",
    locationType: "hybrid",
    employmentType: "contract",
    experienceLevel: "mid",
    postedAt: "2026-07-04",
    responsibilitiesKeys: [
      "items.mechanicalEngineer.responsibilities.0",
      "items.mechanicalEngineer.responsibilities.1",
      "items.mechanicalEngineer.responsibilities.2",
    ],
    requirementsKeys: [
      "items.mechanicalEngineer.requirements.0",
      "items.mechanicalEngineer.requirements.1",
      "items.mechanicalEngineer.requirements.2",
    ],
  },
  {
    id: "job-003",
    categoryId: "healthcare",
    titleKey: "items.registeredNurse.title",
    summaryKey: "items.registeredNurse.summary",
    locationCountry: "UAE",
    locationCity: "Abu Dhabi",
    locationType: "onSite",
    employmentType: "fullTime",
    experienceLevel: "mid",
    postedAt: "2026-07-05",
    responsibilitiesKeys: [
      "items.registeredNurse.responsibilities.0",
      "items.registeredNurse.responsibilities.1",
      "items.registeredNurse.responsibilities.2",
    ],
    requirementsKeys: [
      "items.registeredNurse.requirements.0",
      "items.registeredNurse.requirements.1",
      "items.registeredNurse.requirements.2",
    ],
  },
  {
    id: "job-004",
    categoryId: "logistics",
    titleKey: "items.logisticsCoordinator.title",
    summaryKey: "items.logisticsCoordinator.summary",
    locationCountry: "Saudi Arabia",
    locationCity: "Riyadh",
    locationType: "hybrid",
    employmentType: "fullTime",
    experienceLevel: "mid",
    postedAt: "2026-07-06",
    responsibilitiesKeys: [
      "items.logisticsCoordinator.responsibilities.0",
      "items.logisticsCoordinator.responsibilities.1",
      "items.logisticsCoordinator.responsibilities.2",
    ],
    requirementsKeys: [
      "items.logisticsCoordinator.requirements.0",
      "items.logisticsCoordinator.requirements.1",
      "items.logisticsCoordinator.requirements.2",
    ],
  },
  {
    id: "job-005",
    categoryId: "technology",
    titleKey: "items.frontendEngineer.title",
    summaryKey: "items.frontendEngineer.summary",
    locationCountry: "Tunisia",
    locationCity: "Tunis",
    locationType: "remote",
    employmentType: "contract",
    experienceLevel: "senior",
    postedAt: "2026-07-07",
    responsibilitiesKeys: [
      "items.frontendEngineer.responsibilities.0",
      "items.frontendEngineer.responsibilities.1",
      "items.frontendEngineer.responsibilities.2",
    ],
    requirementsKeys: [
      "items.frontendEngineer.requirements.0",
      "items.frontendEngineer.requirements.1",
      "items.frontendEngineer.requirements.2",
    ],
  },
];