import type { DisclosureFieldCategory, ProtectionAction, ProtectionCategory, ProtectionFindingType, ProtectionLevel } from "../types.ts";
import type { ProtectionRule } from "./types.ts";

const CANDIDATE_MESSAGE =
  "Prime Global protects your personal information and shares only the professional details required at each stage.";

function nowIso(): string {
  return new Date("2026-07-16T00:00:00.000Z").toISOString();
}

function createRule(input: {
  ruleId: string;
  stableRuleKey: string;
  name: string;
  description: string;
  protectedDataCategory: ProtectionCategory;
  findingTypes: ProtectionFindingType[];
  fieldCategories: DisclosureFieldCategory[];
  defaultProtectionLevel?: ProtectionLevel;
  defaultDisclosureState: ProtectionRule["defaultDisclosureState"];
  allowedDisclosureStates: ProtectionRule["allowedDisclosureStates"];
  forbiddenDisclosureStates: ProtectionRule["forbiddenDisclosureStates"];
  immutablePrivacy?: boolean;
  reasonCode: string;
  defaultProtectionAction: ProtectionAction;
  allowedProtectionActions: ProtectionAction[];
  revealEligibility: boolean;
  paymentRequirements?: ProtectionRule["paymentRequirements"];
  contractStateRequirements?: ProtectionRule["contractStateRequirements"];
}): ProtectionRule {
  return {
    ruleId: input.ruleId,
    stableRuleKey: input.stableRuleKey,
    ruleVersion: "1.0.0",
    schemaVersion: "stage8_75.rule.v1",
    lifecycleState: "active",
    name: input.name,
    description: input.description,
    protectedDataCategory: input.protectedDataCategory,
    findingTypes: input.findingTypes,
    fieldCategories: input.fieldCategories,
    defaultProtectionLevel: input.defaultProtectionLevel ?? "strict_private",
    defaultDisclosureState: input.defaultDisclosureState,
    allowedDisclosureStates: input.allowedDisclosureStates,
    forbiddenDisclosureStates: input.forbiddenDisclosureStates,
    immutablePrivacy: input.immutablePrivacy ?? false,
    candidateFriendlyExplanation: CANDIDATE_MESSAGE,
    employerFriendlyExplanation: "Prime Global shares policy-authorized professional details only.",
    internalExplanation: input.description,
    reasonCode: input.reasonCode,
    defaultProtectionAction: input.defaultProtectionAction,
    allowedProtectionActions: input.allowedProtectionActions,
    revealEligibility: input.revealEligibility,
    revealPrerequisites: {
      consentRequired: true,
      staffApprovalRequired: true,
      paymentRequired: input.paymentRequirements === "required",
      contractStateRequired: input.contractStateRequirements ?? "not_required",
    },
    workflowStageConstraints: ["intake", "screening", "matching", "interview", "offer", "contract", "closed"],
    actorRoleConstraints: ["system", "prime_global_staff", "employer"],
    organizationScope: "any",
    tenantScope: "any",
    policyEnginePolicyIds: ["phase10.protection.level.evaluate"],
    businessRuleIds: ["Unlock Contract"],
    consentRequirements: ["consent-v2"],
    staffApprovalRequirements: true,
    paymentRequirements: input.paymentRequirements ?? "not_required",
    contractStateRequirements: input.contractStateRequirements ?? "not_required",
    freezeRestrictions: true,
    criticalViolationRestrictions: true,
    evidenceRequirements: true,
    auditRequirements: true,
    humanReviewRequirements: true,
    falsePositiveHandling: {
      allowCorrection: true,
      allowedOutcomes: ["confirmed", "false_positive", "ignored", "manually_reviewed", "policy_exception"],
    },
    enabled: true,
    effectiveFrom: nowIso(),
    effectiveUntil: null,
    deprecated: false,
    replacementRuleId: null,
    createdAt: nowIso(),
    updatedAt: nowIso(),
    metadata: {},
  };
}

export const initialProtectionRules: ProtectionRule[] = [
  createRule({
    ruleId: "PG-EMAIL-001",
    stableRuleKey: "email-contact",
    name: "Personal Email Protection",
    description: "Masks personal email addresses in recruitment-facing copies.",
    protectedDataCategory: "contact_information",
    findingTypes: ["email"],
    fieldCategories: ["personal_email"],
    defaultDisclosureState: "masked",
    allowedDisclosureStates: ["masked", "staff_only"],
    forbiddenDisclosureStates: ["revealed"],
    reasonCode: "PG-EMAIL-001",
    defaultProtectionAction: "text_redact",
    allowedProtectionActions: ["text_redact"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-PHONE-001",
    stableRuleKey: "phone-contact",
    name: "Personal Phone Protection",
    description: "Masks personal phone numbers in shared outputs.",
    protectedDataCategory: "contact_information",
    findingTypes: ["phone"],
    fieldCategories: ["personal_phone"],
    defaultDisclosureState: "masked",
    allowedDisclosureStates: ["masked", "staff_only"],
    forbiddenDisclosureStates: ["revealed"],
    reasonCode: "PG-PHONE-001",
    defaultProtectionAction: "text_redact",
    allowedProtectionActions: ["text_redact"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-URL-001",
    stableRuleKey: "url-neutralization",
    name: "URL Neutralization",
    description: "Neutralizes direct links unless approved.",
    protectedDataCategory: "linkage",
    findingTypes: ["url"],
    fieldCategories: ["portfolio"],
    defaultProtectionLevel: "protected_recruitment",
    defaultDisclosureState: "protected_placeholder",
    allowedDisclosureStates: ["protected_placeholder", "revealed"],
    forbiddenDisclosureStates: ["hidden"],
    reasonCode: "PG-URL-001",
    defaultProtectionAction: "link_neutralize",
    allowedProtectionActions: ["link_neutralize", "replace_placeholder"],
    revealEligibility: true,
  }),
  createRule({
    ruleId: "PG-SHORT-URL-001",
    stableRuleKey: "short-url-neutralization",
    name: "Short URL Neutralization",
    description: "Neutralizes shortened links in candidate documents.",
    protectedDataCategory: "linkage",
    findingTypes: ["shortened_url"],
    fieldCategories: ["portfolio"],
    defaultDisclosureState: "protected_placeholder",
    allowedDisclosureStates: ["protected_placeholder", "revealed"],
    forbiddenDisclosureStates: ["hidden"],
    reasonCode: "PG-SHORT-URL-001",
    defaultProtectionAction: "link_neutralize",
    allowedProtectionActions: ["link_neutralize", "replace_placeholder"],
    revealEligibility: true,
  }),
  createRule({
    ruleId: "PG-SOCIAL-001",
    stableRuleKey: "social-handle-protection",
    name: "Social Handle Protection",
    description: "Protects social handles until approved disclosure.",
    protectedDataCategory: "contact_information",
    findingTypes: ["social_handle"],
    fieldCategories: ["portfolio"],
    defaultDisclosureState: "protected_placeholder",
    allowedDisclosureStates: ["protected_placeholder", "revealed"],
    forbiddenDisclosureStates: ["staff_only"],
    reasonCode: "PG-SOCIAL-001",
    defaultProtectionAction: "replace_placeholder",
    allowedProtectionActions: ["replace_placeholder", "text_redact"],
    revealEligibility: true,
  }),
  createRule({
    ruleId: "PG-QR-001",
    stableRuleKey: "qr-protection",
    name: "QR Protection",
    description: "Masks QR codes from shared copies.",
    protectedDataCategory: "image_code",
    findingTypes: ["qr_code"],
    fieldCategories: ["private_documents"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed", "masked"],
    immutablePrivacy: true,
    reasonCode: "PG-QR-001",
    defaultProtectionAction: "mask_qr",
    allowedProtectionActions: ["mask_qr"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-BARCODE-001",
    stableRuleKey: "barcode-protection",
    name: "Barcode Protection",
    description: "Masks barcode data from employer-visible outputs.",
    protectedDataCategory: "image_code",
    findingTypes: ["barcode"],
    fieldCategories: ["private_documents"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed", "masked"],
    immutablePrivacy: true,
    reasonCode: "PG-BARCODE-001",
    defaultProtectionAction: "mask_barcode",
    allowedProtectionActions: ["mask_barcode"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-ADDRESS-001",
    stableRuleKey: "address-protection",
    name: "Precise Address Protection",
    description: "Keeps precise address as staff-only by default.",
    protectedDataCategory: "contact_information",
    findingTypes: ["address"],
    fieldCategories: ["precise_address"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed", "summarized"],
    immutablePrivacy: true,
    reasonCode: "PG-ADDRESS-001",
    defaultProtectionAction: "text_redact",
    allowedProtectionActions: ["text_redact"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-PASSPORT-001",
    stableRuleKey: "passport-protection",
    name: "Passport Protection",
    description: "Passport values remain staff-only.",
    protectedDataCategory: "identity_document",
    findingTypes: ["passport_number"],
    fieldCategories: ["passport_number"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed", "masked"],
    immutablePrivacy: true,
    reasonCode: "PG-PASSPORT-001",
    defaultProtectionAction: "text_redact",
    allowedProtectionActions: ["text_redact"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-NATIONAL-ID-001",
    stableRuleKey: "national-id-protection",
    name: "National ID Protection",
    description: "National IDs remain staff-only.",
    protectedDataCategory: "identity_document",
    findingTypes: ["national_id"],
    fieldCategories: ["national_id"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed", "masked"],
    immutablePrivacy: true,
    reasonCode: "PG-NATIONAL-ID-001",
    defaultProtectionAction: "text_redact",
    allowedProtectionActions: ["text_redact"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-PERSONAL-NUMBER-001",
    stableRuleKey: "personal-number-protection",
    name: "Personal Number Protection",
    description: "Protects personal number fields by masking.",
    protectedDataCategory: "identity_document",
    findingTypes: ["personal_number"],
    fieldCategories: ["private_documents"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed"],
    immutablePrivacy: true,
    reasonCode: "PG-PERSONAL-NUMBER-001",
    defaultProtectionAction: "text_redact",
    allowedProtectionActions: ["text_redact"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-CV-PRIVATE-001",
    stableRuleKey: "original-cv-private",
    name: "Original CV Privacy Lock",
    description: "Original CV remains permanently private and unavailable to employers.",
    protectedDataCategory: "identity_document",
    findingTypes: ["unknown_sensitive_pattern"],
    fieldCategories: ["original_cv"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed", "masked", "summarized", "protected_placeholder"],
    immutablePrivacy: true,
    reasonCode: "PG-CV-PRIVATE-001",
    defaultProtectionAction: "replace_placeholder",
    allowedProtectionActions: ["replace_placeholder"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-PRIVATE-DOCUMENT-001",
    stableRuleKey: "private-document-lock",
    name: "Private Document Privacy Lock",
    description: "Private candidate documents remain unavailable to employers.",
    protectedDataCategory: "identity_document",
    findingTypes: ["unknown_sensitive_pattern"],
    fieldCategories: ["private_documents"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed", "masked", "summarized", "protected_placeholder"],
    immutablePrivacy: true,
    reasonCode: "PG-PRIVATE-DOCUMENT-001",
    defaultProtectionAction: "replace_placeholder",
    allowedProtectionActions: ["replace_placeholder"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-METADATA-001",
    stableRuleKey: "metadata-protection",
    name: "Metadata Protection",
    description: "Strips hidden metadata from shared outputs.",
    protectedDataCategory: "metadata",
    findingTypes: ["hidden_metadata"],
    fieldCategories: ["private_documents"],
    defaultDisclosureState: "staff_only",
    allowedDisclosureStates: ["staff_only"],
    forbiddenDisclosureStates: ["revealed"],
    immutablePrivacy: true,
    reasonCode: "PG-METADATA-001",
    defaultProtectionAction: "metadata_strip",
    allowedProtectionActions: ["metadata_strip"],
    revealEligibility: false,
  }),
  createRule({
    ruleId: "PG-EXTERNAL-MEETING-001",
    stableRuleKey: "external-meeting-link",
    name: "External Meeting Link Protection",
    description: "Neutralizes external meeting links unless approved.",
    protectedDataCategory: "linkage",
    findingTypes: ["external_meeting_link"],
    fieldCategories: ["portfolio"],
    defaultDisclosureState: "protected_placeholder",
    allowedDisclosureStates: ["protected_placeholder", "revealed"],
    forbiddenDisclosureStates: ["hidden"],
    reasonCode: "PG-EXTERNAL-MEETING-001",
    defaultProtectionAction: "link_neutralize",
    allowedProtectionActions: ["link_neutralize", "replace_placeholder"],
    revealEligibility: true,
  }),
  createRule({
    ruleId: "PG-CONTRACT-REVEAL-001",
    stableRuleKey: "contract-reveal",
    name: "Contract Stage Limited Reveal",
    description: "Allows limited reveal for approved professional fields during contract stage.",
    protectedDataCategory: "unknown",
    findingTypes: ["unknown_sensitive_pattern"],
    fieldCategories: ["professional_name", "portfolio", "general_location"],
    defaultProtectionLevel: "contract_stage_limited_reveal",
    defaultDisclosureState: "protected_placeholder",
    allowedDisclosureStates: ["protected_placeholder", "revealed", "summarized"],
    forbiddenDisclosureStates: ["staff_only"],
    reasonCode: "PG-CONTRACT-REVEAL-001",
    defaultProtectionAction: "replace_placeholder",
    allowedProtectionActions: ["replace_placeholder"],
    revealEligibility: true,
    paymentRequirements: "required",
    contractStateRequirements: "must_be_signed",
  }),
  createRule({
    ruleId: "PG-PORTFOLIO-REVEAL-001",
    stableRuleKey: "portfolio-reveal",
    name: "Portfolio Reveal Control",
    description: "Controls reveal of portfolio links after approval.",
    protectedDataCategory: "linkage",
    findingTypes: ["url", "shortened_url"],
    fieldCategories: ["portfolio"],
    defaultDisclosureState: "protected_placeholder",
    allowedDisclosureStates: ["protected_placeholder", "revealed"],
    forbiddenDisclosureStates: ["staff_only"],
    reasonCode: "PG-PORTFOLIO-REVEAL-001",
    defaultProtectionAction: "replace_placeholder",
    allowedProtectionActions: ["replace_placeholder"],
    revealEligibility: true,
  }),
  createRule({
    ruleId: "PG-PROFESSIONAL-NAME-001",
    stableRuleKey: "professional-name-reveal",
    name: "Professional Name Reveal Control",
    description: "Allows professional name reveal only after policy checks.",
    protectedDataCategory: "contact_information",
    findingTypes: ["unknown_sensitive_pattern"],
    fieldCategories: ["professional_name"],
    defaultDisclosureState: "protected_placeholder",
    allowedDisclosureStates: ["protected_placeholder", "revealed"],
    forbiddenDisclosureStates: ["staff_only"],
    reasonCode: "PG-PROFESSIONAL-NAME-001",
    defaultProtectionAction: "replace_placeholder",
    allowedProtectionActions: ["replace_placeholder"],
    revealEligibility: true,
  }),
  createRule({
    ruleId: "PG-GENERAL-LOCATION-001",
    stableRuleKey: "general-location-reveal",
    name: "General Location Summary",
    description: "Allows generalized location summary for approved stages.",
    protectedDataCategory: "contact_information",
    findingTypes: ["address"],
    fieldCategories: ["general_location"],
    defaultDisclosureState: "summarized",
    allowedDisclosureStates: ["summarized", "revealed"],
    forbiddenDisclosureStates: ["staff_only"],
    reasonCode: "PG-GENERAL-LOCATION-001",
    defaultProtectionAction: "replace_placeholder",
    allowedProtectionActions: ["replace_placeholder", "text_redact"],
    revealEligibility: true,
  }),
  createRule({
    ruleId: "PG-WORK-AUTHORIZATION-001",
    stableRuleKey: "work-authorization-reveal",
    name: "Work Authorization Reveal Control",
    description: "Shares work authorization details at policy-approved stages.",
    protectedDataCategory: "identity_document",
    findingTypes: ["unknown_sensitive_pattern"],
    fieldCategories: ["work_authorization"],
    defaultDisclosureState: "summarized",
    allowedDisclosureStates: ["summarized", "revealed"],
    forbiddenDisclosureStates: ["staff_only"],
    reasonCode: "PG-WORK-AUTHORIZATION-001",
    defaultProtectionAction: "replace_placeholder",
    allowedProtectionActions: ["replace_placeholder"],
    revealEligibility: true,
    contractStateRequirements: "required",
  }),
];
