import type { AiFallbackPolicy, AiTaskPolicy, AiTaskType } from "../contracts/types.ts";

const VERSION = "milestone1-static-v1";

export const DEFAULT_TASK_POLICIES: Record<AiTaskType, AiTaskPolicy> = {
  cv_extract: {
    taskType: "cv_extract",
    requiredCapability: "generate_json",
    primaryProvider: "local_llm",
    fallbackChain: ["local_llm"],
    modelClass: "reasoning",
    temperature: 0.1,
    timeoutMs: 45_000,
    retryCount: 1,
    requireJson: true,
    piiSensitivity: "restricted",
    allowExternalProviders: false,
    localLlmPreference: "mandatory",
    enabled: true,
    policyVersion: VERSION,
  },
  profile_rewrite: {
    taskType: "profile_rewrite",
    requiredCapability: "generate_text",
    primaryProvider: "openai",
    fallbackChain: ["anthropic_claude", "google_gemini", "deepseek", "local_llm"],
    modelClass: "standard",
    temperature: 0.4,
    timeoutMs: 20_000,
    retryCount: 2,
    requireJson: false,
    piiSensitivity: "medium",
    allowExternalProviders: true,
    localLlmPreference: "optional",
    enabled: true,
    policyVersion: VERSION,
  },
  recommendations: {
    taskType: "recommendations",
    requiredCapability: "generate_json",
    primaryProvider: "google_gemini",
    fallbackChain: ["deepseek", "openai", "anthropic_claude", "local_llm"],
    modelClass: "mini",
    temperature: 0.3,
    timeoutMs: 18_000,
    retryCount: 2,
    requireJson: true,
    piiSensitivity: "medium",
    allowExternalProviders: true,
    localLlmPreference: "preferred",
    enabled: true,
    policyVersion: VERSION,
  },
  matching_explanation: {
    taskType: "matching_explanation",
    requiredCapability: "generate_text",
    primaryProvider: "anthropic_claude",
    fallbackChain: ["openai", "google_gemini", "deepseek", "local_llm"],
    modelClass: "standard",
    temperature: 0.2,
    timeoutMs: 15_000,
    retryCount: 1,
    requireJson: false,
    piiSensitivity: "low",
    allowExternalProviders: true,
    localLlmPreference: "optional",
    enabled: true,
    policyVersion: VERSION,
  },
  skill_normalization: {
    taskType: "skill_normalization",
    requiredCapability: "classify",
    primaryProvider: "local_llm",
    fallbackChain: ["deepseek", "openai"],
    modelClass: "standard",
    temperature: 0,
    timeoutMs: 12_000,
    retryCount: 1,
    requireJson: true,
    piiSensitivity: "medium",
    allowExternalProviders: false,
    localLlmPreference: "preferred",
    enabled: true,
    policyVersion: VERSION,
  },
  pii_detection: {
    taskType: "pii_detection",
    requiredCapability: "classify",
    primaryProvider: "local_llm",
    fallbackChain: ["local_llm"],
    modelClass: "standard",
    temperature: 0,
    timeoutMs: 8_000,
    retryCount: 0,
    requireJson: true,
    piiSensitivity: "restricted",
    allowExternalProviders: false,
    localLlmPreference: "mandatory",
    enabled: true,
    policyVersion: VERSION,
  },
  employer_summary: {
    taskType: "employer_summary",
    requiredCapability: "generate_text",
    primaryProvider: "openai",
    fallbackChain: ["anthropic_claude", "google_gemini", "deepseek", "local_llm"],
    modelClass: "mini",
    temperature: 0.2,
    timeoutMs: 15_000,
    retryCount: 1,
    requireJson: false,
    piiSensitivity: "medium",
    allowExternalProviders: true,
    localLlmPreference: "optional",
    enabled: true,
    policyVersion: VERSION,
  },
  candidate_rescoring: {
    taskType: "candidate_rescoring",
    requiredCapability: "generate_json",
    primaryProvider: "local_llm",
    fallbackChain: ["local_llm"],
    modelClass: "reasoning",
    temperature: 0,
    timeoutMs: 25_000,
    retryCount: 1,
    requireJson: true,
    piiSensitivity: "high",
    allowExternalProviders: false,
    localLlmPreference: "mandatory",
    enabled: true,
    policyVersion: VERSION,
  },
};

export const DEFAULT_FALLBACK_POLICIES: Record<AiTaskType, AiFallbackPolicy> = {
  cv_extract: {
    taskType: "cv_extract",
    maxFallbackDepth: 0,
    stopOnPolicyBlock: true,
    stopOnSchemaFailure: true,
    allowProviderReuseAfterRateLimit: false,
    allowExternalFallbackForHighSensitivity: false,
    order: ["local_llm"],
  },
  profile_rewrite: {
    taskType: "profile_rewrite",
    maxFallbackDepth: 4,
    stopOnPolicyBlock: true,
    stopOnSchemaFailure: true,
    allowProviderReuseAfterRateLimit: false,
    allowExternalFallbackForHighSensitivity: false,
    order: ["openai", "anthropic_claude", "google_gemini", "deepseek", "local_llm"],
  },
  recommendations: {
    taskType: "recommendations",
    maxFallbackDepth: 4,
    stopOnPolicyBlock: true,
    stopOnSchemaFailure: true,
    allowProviderReuseAfterRateLimit: false,
    allowExternalFallbackForHighSensitivity: false,
    order: ["google_gemini", "deepseek", "openai", "anthropic_claude", "local_llm"],
  },
  matching_explanation: {
    taskType: "matching_explanation",
    maxFallbackDepth: 4,
    stopOnPolicyBlock: true,
    stopOnSchemaFailure: false,
    allowProviderReuseAfterRateLimit: false,
    allowExternalFallbackForHighSensitivity: false,
    order: ["anthropic_claude", "openai", "google_gemini", "deepseek", "local_llm"],
  },
  skill_normalization: {
    taskType: "skill_normalization",
    maxFallbackDepth: 2,
    stopOnPolicyBlock: true,
    stopOnSchemaFailure: true,
    allowProviderReuseAfterRateLimit: false,
    allowExternalFallbackForHighSensitivity: false,
    order: ["local_llm", "deepseek", "openai"],
  },
  pii_detection: {
    taskType: "pii_detection",
    maxFallbackDepth: 0,
    stopOnPolicyBlock: true,
    stopOnSchemaFailure: true,
    allowProviderReuseAfterRateLimit: false,
    allowExternalFallbackForHighSensitivity: false,
    order: ["local_llm"],
  },
  employer_summary: {
    taskType: "employer_summary",
    maxFallbackDepth: 4,
    stopOnPolicyBlock: true,
    stopOnSchemaFailure: false,
    allowProviderReuseAfterRateLimit: false,
    allowExternalFallbackForHighSensitivity: false,
    order: ["openai", "anthropic_claude", "google_gemini", "deepseek", "local_llm"],
  },
  candidate_rescoring: {
    taskType: "candidate_rescoring",
    maxFallbackDepth: 0,
    stopOnPolicyBlock: true,
    stopOnSchemaFailure: true,
    allowProviderReuseAfterRateLimit: false,
    allowExternalFallbackForHighSensitivity: false,
    order: ["local_llm"],
  },
};