import type { Phase10FeatureFlags } from "../../feature-flags/index.ts";

export interface DocumentAnalysisFeatureFlags {
  DOCUMENT_ANALYSIS_ENABLED: boolean;
  IMAGE_ANALYSIS_ENABLED: boolean;
  PDF_TEXT_EXTRACTION_ENABLED: boolean;
  DOCX_TEXT_EXTRACTION_ENABLED: boolean;
  QR_ANALYSIS_ENABLED: boolean;
  BARCODE_ANALYSIS_ENABLED: boolean;
  METADATA_PROTECTION_ENABLED: boolean;
  DOCUMENT_QUARANTINE_ENABLED: boolean;
  PROTECTION_PLAN_ENABLED: boolean;
  DOCUMENT_REVIEW_ENABLED: boolean;
  ADAPTIVE_PROTECTION_ENABLED: boolean;
  EXPLAINABLE_PROTECTION_ENABLED: boolean;
  REVERSIBLE_PROTECTION_ENABLED: boolean;
  FIELD_LEVEL_DISCLOSURE_ENABLED: boolean;
  PARTIAL_REVEAL_ENABLED: boolean;
  REVEAL_APPROVAL_ENABLED: boolean;
  DISCLOSURE_MANIFEST_ENABLED: boolean;
}

export function getDocumentAnalysisFeatureFlags(flags: Phase10FeatureFlags): DocumentAnalysisFeatureFlags {
  return {
    DOCUMENT_ANALYSIS_ENABLED: flags.DOCUMENT_ANALYSIS_ENABLED,
    IMAGE_ANALYSIS_ENABLED: flags.IMAGE_ANALYSIS_ENABLED,
    PDF_TEXT_EXTRACTION_ENABLED: flags.PDF_TEXT_EXTRACTION_ENABLED,
    DOCX_TEXT_EXTRACTION_ENABLED: flags.DOCX_TEXT_EXTRACTION_ENABLED,
    QR_ANALYSIS_ENABLED: flags.QR_ANALYSIS_ENABLED,
    BARCODE_ANALYSIS_ENABLED: flags.BARCODE_ANALYSIS_ENABLED,
    METADATA_PROTECTION_ENABLED: flags.METADATA_PROTECTION_ENABLED,
    DOCUMENT_QUARANTINE_ENABLED: flags.DOCUMENT_QUARANTINE_ENABLED,
    PROTECTION_PLAN_ENABLED: flags.PROTECTION_PLAN_ENABLED,
    DOCUMENT_REVIEW_ENABLED: flags.DOCUMENT_REVIEW_ENABLED,
    ADAPTIVE_PROTECTION_ENABLED: flags.ADAPTIVE_PROTECTION_ENABLED,
    EXPLAINABLE_PROTECTION_ENABLED: flags.EXPLAINABLE_PROTECTION_ENABLED,
    REVERSIBLE_PROTECTION_ENABLED: flags.REVERSIBLE_PROTECTION_ENABLED,
    FIELD_LEVEL_DISCLOSURE_ENABLED: flags.FIELD_LEVEL_DISCLOSURE_ENABLED,
    PARTIAL_REVEAL_ENABLED: flags.PARTIAL_REVEAL_ENABLED,
    REVEAL_APPROVAL_ENABLED: flags.REVEAL_APPROVAL_ENABLED,
    DISCLOSURE_MANIFEST_ENABLED: flags.DISCLOSURE_MANIFEST_ENABLED,
  };
}

export function createAllEnabledDocumentAnalysisFlags(): DocumentAnalysisFeatureFlags {
  return {
    DOCUMENT_ANALYSIS_ENABLED: true,
    IMAGE_ANALYSIS_ENABLED: true,
    PDF_TEXT_EXTRACTION_ENABLED: true,
    DOCX_TEXT_EXTRACTION_ENABLED: true,
    QR_ANALYSIS_ENABLED: true,
    BARCODE_ANALYSIS_ENABLED: true,
    METADATA_PROTECTION_ENABLED: true,
    DOCUMENT_QUARANTINE_ENABLED: true,
    PROTECTION_PLAN_ENABLED: true,
    DOCUMENT_REVIEW_ENABLED: true,
    ADAPTIVE_PROTECTION_ENABLED: true,
    EXPLAINABLE_PROTECTION_ENABLED: true,
    REVERSIBLE_PROTECTION_ENABLED: true,
    FIELD_LEVEL_DISCLOSURE_ENABLED: true,
    PARTIAL_REVEAL_ENABLED: true,
    REVEAL_APPROVAL_ENABLED: true,
    DISCLOSURE_MANIFEST_ENABLED: true,
  };
}
