import type { Phase10FeatureFlags } from "../../feature-flags/index.ts";

export interface DocumentAnalysisFeatureFlags {
  DOCUMENT_ANALYSIS_ENABLED: boolean;
  IMAGE_ANALYSIS_ENABLED: boolean;
  PDF_TEXT_EXTRACTION_ENABLED: boolean;
  DOCX_TEXT_EXTRACTION_ENABLED: boolean;
  QR_ANALYSIS_ENABLED: boolean;
  BARCODE_ANALYSIS_ENABLED: boolean;
  METADATA_PROTECTION_ENABLED: boolean;
  DOCUMENT_QUARANTINE_ENABLED: boolean;
  PROTECTION_PLAN_ENABLED: boolean;
  DOCUMENT_REVIEW_ENABLED: boolean;
}

export function getDocumentAnalysisFeatureFlags(flags: Phase10FeatureFlags): DocumentAnalysisFeatureFlags {
  return {
    DOCUMENT_ANALYSIS_ENABLED: flags.DOCUMENT_ANALYSIS_ENABLED,
    IMAGE_ANALYSIS_ENABLED: flags.IMAGE_ANALYSIS_ENABLED,
    PDF_TEXT_EXTRACTION_ENABLED: flags.PDF_TEXT_EXTRACTION_ENABLED,
    DOCX_TEXT_EXTRACTION_ENABLED: flags.DOCX_TEXT_EXTRACTION_ENABLED,
    QR_ANALYSIS_ENABLED: flags.QR_ANALYSIS_ENABLED,
    BARCODE_ANALYSIS_ENABLED: flags.BARCODE_ANALYSIS_ENABLED,
    METADATA_PROTECTION_ENABLED: flags.METADATA_PROTECTION_ENABLED,
    DOCUMENT_QUARANTINE_ENABLED: flags.DOCUMENT_QUARANTINE_ENABLED,
    PROTECTION_PLAN_ENABLED: flags.PROTECTION_PLAN_ENABLED,
    DOCUMENT_REVIEW_ENABLED: flags.DOCUMENT_REVIEW_ENABLED,
  };
}

export function createAllEnabledDocumentAnalysisFlags(): DocumentAnalysisFeatureFlags {
  return {
    DOCUMENT_ANALYSIS_ENABLED: true,
    IMAGE_ANALYSIS_ENABLED: true,
    PDF_TEXT_EXTRACTION_ENABLED: true,
    DOCX_TEXT_EXTRACTION_ENABLED: true,
    QR_ANALYSIS_ENABLED: true,
    BARCODE_ANALYSIS_ENABLED: true,
    METADATA_PROTECTION_ENABLED: true,
    DOCUMENT_QUARANTINE_ENABLED: true,
    PROTECTION_PLAN_ENABLED: true,
    DOCUMENT_REVIEW_ENABLED: true,
  };
}
