import type { Phase10FeatureFlags } from "../../feature-flags/index.ts";

export interface DocumentAnalysisFeatureFlags {
  DOCUMENT_ANALYSIS_ENABLED: boolean;
  IMAGE_ANALYSIS_ENABLED: boolean;
  PDF_TEXT_EXTRACTION_ENABLED: boolean;
  DOCX_TEXT_EXTRACTION_ENABLED: boolean;
  QR_ANALYSIS_ENABLED: boolean;
  BARCODE_ANALYSIS_ENABLED: boolean;
  METADATA_PROTECTION_ENABLED: boolean;
  DOCUMENT_QUARANTINE_ENABLED: boolean;
  PROTECTION_PLAN_ENABLED: boolean;
  DOCUMENT_REVIEW_ENABLED: boolean;
  ADAPTIVE_PROTECTION_ENABLED: boolean;
  EXPLAINABLE_PROTECTION_ENABLED: boolean;
  REVERSIBLE_PROTECTION_ENABLED: boolean;
  FIELD_LEVEL_DISCLOSURE_ENABLED: boolean;
  PARTIAL_REVEAL_ENABLED: boolean;
  REVEAL_APPROVAL_ENABLED: boolean;
  DISCLOSURE_MANIFEST_ENABLED: boolean;
  PROTECTION_RULES_REGISTRY_ENABLED: boolean;
  PROTECTION_RULE_VERSIONING_ENABLED: boolean;
  PROTECTION_RULE_RESOLUTION_ENABLED: boolean;
  PROTECTION_RULE_GOVERNANCE_ENABLED: boolean;
  PROTECTION_RULE_SNAPSHOTS_ENABLED: boolean;
  CONTACT_PROTECTION_ENABLED: boolean;
  EMAIL_PROTECTION_ENABLED: boolean;
  PHONE_PROTECTION_ENABLED: boolean;
  SOCIAL_CONTACT_PROTECTION_ENABLED: boolean;
  EXTERNAL_LINK_PROTECTION_ENABLED: boolean;
  MEETING_LINK_PROTECTION_ENABLED: boolean;
  SHORT_URL_PROTECTION_ENABLED: boolean;
  OBFUSCATION_PROTECTION_ENABLED: boolean;
  UNICODE_HOMOGLYPH_PROTECTION_ENABLED: boolean;
  ENCODED_CONTENT_PROTECTION_ENABLED: boolean;
  CROSS_MESSAGE_PROTECTION_ENABLED: boolean;
  MESSAGE_PROTECTED_PROJECTION_ENABLED: boolean;
  JOB_AD_CONTACT_PROTECTION_ENABLED: boolean;
  PROFILE_CONTACT_PROTECTION_ENABLED: boolean;
}

export function getDocumentAnalysisFeatureFlags(flags: Phase10FeatureFlags): DocumentAnalysisFeatureFlags {
  return {
    DOCUMENT_ANALYSIS_ENABLED: flags.DOCUMENT_ANALYSIS_ENABLED,
    IMAGE_ANALYSIS_ENABLED: flags.IMAGE_ANALYSIS_ENABLED,
    PDF_TEXT_EXTRACTION_ENABLED: flags.PDF_TEXT_EXTRACTION_ENABLED,
    DOCX_TEXT_EXTRACTION_ENABLED: flags.DOCX_TEXT_EXTRACTION_ENABLED,
    QR_ANALYSIS_ENABLED: flags.QR_ANALYSIS_ENABLED,
    BARCODE_ANALYSIS_ENABLED: flags.BARCODE_ANALYSIS_ENABLED,
    METADATA_PROTECTION_ENABLED: flags.METADATA_PROTECTION_ENABLED,
    DOCUMENT_QUARANTINE_ENABLED: flags.DOCUMENT_QUARANTINE_ENABLED,
    PROTECTION_PLAN_ENABLED: flags.PROTECTION_PLAN_ENABLED,
    DOCUMENT_REVIEW_ENABLED: flags.DOCUMENT_REVIEW_ENABLED,
    ADAPTIVE_PROTECTION_ENABLED: flags.ADAPTIVE_PROTECTION_ENABLED,
    EXPLAINABLE_PROTECTION_ENABLED: flags.EXPLAINABLE_PROTECTION_ENABLED,
    REVERSIBLE_PROTECTION_ENABLED: flags.REVERSIBLE_PROTECTION_ENABLED,
    FIELD_LEVEL_DISCLOSURE_ENABLED: flags.FIELD_LEVEL_DISCLOSURE_ENABLED,
    PARTIAL_REVEAL_ENABLED: flags.PARTIAL_REVEAL_ENABLED,
    REVEAL_APPROVAL_ENABLED: flags.REVEAL_APPROVAL_ENABLED,
    DISCLOSURE_MANIFEST_ENABLED: flags.DISCLOSURE_MANIFEST_ENABLED,
    PROTECTION_RULES_REGISTRY_ENABLED: flags.PROTECTION_RULES_REGISTRY_ENABLED,
    PROTECTION_RULE_VERSIONING_ENABLED: flags.PROTECTION_RULE_VERSIONING_ENABLED,
    PROTECTION_RULE_RESOLUTION_ENABLED: flags.PROTECTION_RULE_RESOLUTION_ENABLED,
    PROTECTION_RULE_GOVERNANCE_ENABLED: flags.PROTECTION_RULE_GOVERNANCE_ENABLED,
    PROTECTION_RULE_SNAPSHOTS_ENABLED: flags.PROTECTION_RULE_SNAPSHOTS_ENABLED,
    CONTACT_PROTECTION_ENABLED: flags.CONTACT_PROTECTION_ENABLED,
    EMAIL_PROTECTION_ENABLED: flags.EMAIL_PROTECTION_ENABLED,
    PHONE_PROTECTION_ENABLED: flags.PHONE_PROTECTION_ENABLED,
    SOCIAL_CONTACT_PROTECTION_ENABLED: flags.SOCIAL_CONTACT_PROTECTION_ENABLED,
    EXTERNAL_LINK_PROTECTION_ENABLED: flags.EXTERNAL_LINK_PROTECTION_ENABLED,
    MEETING_LINK_PROTECTION_ENABLED: flags.MEETING_LINK_PROTECTION_ENABLED,
    SHORT_URL_PROTECTION_ENABLED: flags.SHORT_URL_PROTECTION_ENABLED,
    OBFUSCATION_PROTECTION_ENABLED: flags.OBFUSCATION_PROTECTION_ENABLED,
    UNICODE_HOMOGLYPH_PROTECTION_ENABLED: flags.UNICODE_HOMOGLYPH_PROTECTION_ENABLED,
    ENCODED_CONTENT_PROTECTION_ENABLED: flags.ENCODED_CONTENT_PROTECTION_ENABLED,
    CROSS_MESSAGE_PROTECTION_ENABLED: flags.CROSS_MESSAGE_PROTECTION_ENABLED,
    MESSAGE_PROTECTED_PROJECTION_ENABLED: flags.MESSAGE_PROTECTED_PROJECTION_ENABLED,
    JOB_AD_CONTACT_PROTECTION_ENABLED: flags.JOB_AD_CONTACT_PROTECTION_ENABLED,
    PROFILE_CONTACT_PROTECTION_ENABLED: flags.PROFILE_CONTACT_PROTECTION_ENABLED,
  };
}

export function createAllEnabledDocumentAnalysisFlags(): DocumentAnalysisFeatureFlags {
  return {
    DOCUMENT_ANALYSIS_ENABLED: true,
    IMAGE_ANALYSIS_ENABLED: true,
    PDF_TEXT_EXTRACTION_ENABLED: true,
    DOCX_TEXT_EXTRACTION_ENABLED: true,
    QR_ANALYSIS_ENABLED: true,
    BARCODE_ANALYSIS_ENABLED: true,
    METADATA_PROTECTION_ENABLED: true,
    DOCUMENT_QUARANTINE_ENABLED: true,
    PROTECTION_PLAN_ENABLED: true,
    DOCUMENT_REVIEW_ENABLED: true,
    ADAPTIVE_PROTECTION_ENABLED: true,
    EXPLAINABLE_PROTECTION_ENABLED: true,
    REVERSIBLE_PROTECTION_ENABLED: true,
    FIELD_LEVEL_DISCLOSURE_ENABLED: true,
    PARTIAL_REVEAL_ENABLED: true,
    REVEAL_APPROVAL_ENABLED: true,
    DISCLOSURE_MANIFEST_ENABLED: true,
    PROTECTION_RULES_REGISTRY_ENABLED: true,
    PROTECTION_RULE_VERSIONING_ENABLED: true,
    PROTECTION_RULE_RESOLUTION_ENABLED: true,
    PROTECTION_RULE_GOVERNANCE_ENABLED: true,
    PROTECTION_RULE_SNAPSHOTS_ENABLED: true,
    CONTACT_PROTECTION_ENABLED: true,
    EMAIL_PROTECTION_ENABLED: true,
    PHONE_PROTECTION_ENABLED: true,
    SOCIAL_CONTACT_PROTECTION_ENABLED: true,
    EXTERNAL_LINK_PROTECTION_ENABLED: true,
    MEETING_LINK_PROTECTION_ENABLED: true,
    SHORT_URL_PROTECTION_ENABLED: true,
    OBFUSCATION_PROTECTION_ENABLED: true,
    UNICODE_HOMOGLYPH_PROTECTION_ENABLED: true,
    ENCODED_CONTENT_PROTECTION_ENABLED: true,
    CROSS_MESSAGE_PROTECTION_ENABLED: true,
    MESSAGE_PROTECTED_PROJECTION_ENABLED: true,
    JOB_AD_CONTACT_PROTECTION_ENABLED: true,
    PROFILE_CONTACT_PROTECTION_ENABLED: true,
  };
}
