import type { FinancialPermissionCode } from "./types.ts";

export const financialPermissionMatrix: Record<string, FinancialPermissionCode[]> = {
  owner: [
    "financial.accounts.read",
    "financial.accounts.write",
    "financial.ledger.post",
    "financial.ledger.void",
    "financial.invoices.read",
    "financial.invoices.issue",
    "financial.invoices.adjust",
    "financial.subscriptions.manage",
    "financial.payments.manage",
    "financial.refunds.manage",
    "financial.disputes.manage",
    "financial.reconciliation.manage",
    "financial.tax.manage",
    "financial.commission.manage",
    "financial.audit.read",
    "financial.approvals.manage",
  ],
  ceo: [
    "financial.accounts.read",
    "financial.ledger.post",
    "financial.invoices.read",
    "financial.invoices.issue",
    "financial.subscriptions.manage",
    "financial.payments.manage",
    "financial.refunds.manage",
    "financial.disputes.manage",
    "financial.reconciliation.manage",
    "financial.tax.manage",
    "financial.commission.manage",
    "financial.audit.read",
    "financial.approvals.manage",
  ],
  cfo: [
    "financial.accounts.read",
    "financial.accounts.write",
    "financial.ledger.post",
    "financial.ledger.void",
    "financial.invoices.read",
    "financial.invoices.issue",
    "financial.invoices.adjust",
    "financial.subscriptions.manage",
    "financial.payments.manage",
    "financial.refunds.manage",
    "financial.disputes.manage",
    "financial.reconciliation.manage",
    "financial.tax.manage",
    "financial.commission.manage",
    "financial.audit.read",
    "financial.approvals.manage",
  ],
  coo: [
    "financial.accounts.read",
    "financial.invoices.read",
    "financial.subscriptions.manage",
    "financial.payments.manage",
    "financial.reconciliation.manage",
    "financial.audit.read",
  ],
  super_admin: [
    "financial.accounts.read",
    "financial.accounts.write",
    "financial.ledger.post",
    "financial.invoices.read",
    "financial.invoices.issue",
    "financial.subscriptions.manage",
    "financial.payments.manage",
    "financial.refunds.manage",
    "financial.disputes.manage",
    "financial.reconciliation.manage",
    "financial.tax.manage",
    "financial.commission.manage",
    "financial.audit.read",
  ],
  department_manager: [
    "financial.invoices.read",
    "financial.subscriptions.manage",
    "financial.payments.manage",
  ],
  read_only_auditor: ["financial.accounts.read", "financial.invoices.read", "financial.audit.read"],
};

export function listFinancialPermissionsForRole(roleCode: string) {
  return financialPermissionMatrix[roleCode] ?? [];
}
