import type { ObservabilityPermissionCode } from "./types.ts";

export const observabilityPermissionMatrix: Record<string, ObservabilityPermissionCode[]> = {
  owner: [
    "ops.monitoring.read",
    "ops.monitoring.manage",
    "ops.logging.read",
    "ops.logging.manage",
    "ops.metrics.read",
    "ops.metrics.manage",
    "ops.tracing.read",
    "ops.health.manage",
    "ops.incidents.manage",
    "ops.flags.manage",
    "ops.config.manage",
    "ops.backup.manage",
    "ops.performance.manage",
    "ops.reliability.manage",
    "ops.securityops.manage",
    "ops.audit.read",
  ],
  ceo: [
    "ops.monitoring.read",
    "ops.logging.read",
    "ops.metrics.read",
    "ops.tracing.read",
    "ops.health.manage",
    "ops.incidents.manage",
    "ops.performance.manage",
    "ops.reliability.manage",
    "ops.audit.read",
  ],
  cto: [
    "ops.monitoring.read",
    "ops.monitoring.manage",
    "ops.logging.read",
    "ops.logging.manage",
    "ops.metrics.read",
    "ops.metrics.manage",
    "ops.tracing.read",
    "ops.health.manage",
    "ops.incidents.manage",
    "ops.flags.manage",
    "ops.config.manage",
    "ops.performance.manage",
    "ops.reliability.manage",
    "ops.audit.read",
  ],
  sre_lead: [
    "ops.monitoring.read",
    "ops.monitoring.manage",
    "ops.logging.read",
    "ops.logging.manage",
    "ops.metrics.read",
    "ops.metrics.manage",
    "ops.tracing.read",
    "ops.health.manage",
    "ops.incidents.manage",
    "ops.flags.manage",
    "ops.config.manage",
    "ops.backup.manage",
    "ops.performance.manage",
    "ops.reliability.manage",
    "ops.securityops.manage",
    "ops.audit.read",
  ],
  super_admin: [
    "ops.monitoring.read",
    "ops.monitoring.manage",
    "ops.logging.read",
    "ops.metrics.read",
    "ops.health.manage",
    "ops.incidents.manage",
    "ops.flags.manage",
    "ops.config.manage",
    "ops.backup.manage",
    "ops.performance.manage",
    "ops.reliability.manage",
    "ops.securityops.manage",
    "ops.audit.read",
  ],
  department_manager: ["ops.monitoring.read", "ops.metrics.read", "ops.health.manage", "ops.incidents.manage"],
  read_only_auditor: ["ops.monitoring.read", "ops.logging.read", "ops.metrics.read", "ops.tracing.read", "ops.audit.read"],
};

export function listObservabilityPermissionsForRole(roleCode: string) {
  return observabilityPermissionMatrix[roleCode] ?? [];
}
