import type { Phase10FeatureFlagSnapshot, Phase10FeatureFlags, Phase10FeatureFlagName } from "./types.ts";

const DEFAULT_PHASE10_FLAGS: Phase10FeatureFlags = {
  PRIME_SHIELD_ENABLED: false,
  PROTECTED_INTERVIEWS_ENABLED: false,
  SHIELD_ATTACHMENT_SCANNING_ENABLED: false,
  SHIELD_PROGRESSIVE_ENFORCEMENT_ENABLED: false,
  RECRUITMENT_TIMELINE_ENABLED: false,
  CIRCUMVENTION_RISK_ENABLED: false,
  AI_RECRUITER_ASSISTANT_ENABLED: false,
  AI_CANDIDATE_COACH_ENABLED: false,
  VIDEO_ROOMS_ENABLED: false,
  SERVICE_FEE_GATE_ENABLED: false,
  GOVERNANCE_CENTER_ENABLED: false,
  ENTERPRISE_SLA_ENABLED: false,
  TENANT_ABSTRACTION_ENABLED: false,
  SHIELD_INFRA_FOUNDATION_ENABLED: false,
  SHIELD_INTEGRITY_MONITOR_ENABLED: false,
  SHIELD_EVENT_REPLAY_ENABLED: false,
  SHIELD_EVIDENCE_VERSIONING_ENABLED: false,
  SHIELD_MIGRATION_COMPATIBILITY_ENABLED: false,
  WORKFLOW_KERNEL_ENABLED: false,
  WORKFLOW_COMMANDS_ENABLED: false,
  WORKFLOW_QUERIES_ENABLED: false,
  WORKFLOW_IDEMPOTENCY_ENABLED: false,
  WORKFLOW_LOCKING_ENABLED: false,
  WORKFLOW_OPTIMISTIC_LOCKING_ENABLED: false,
  WORKFLOW_COMPENSATION_ENABLED: false,
  WORKFLOW_EVENT_REPLAY_ENABLED: false,
  RECRUITMENT_ORCHESTRATOR_ENABLED: false,
  ORCHESTRATION_SAGAS_ENABLED: false,
  ORCHESTRATION_GRAPHS_ENABLED: false,
  ORCHESTRATION_SNAPSHOTS_ENABLED: false,
  ORCHESTRATION_RECOVERY_ENABLED: false,
  ORCHESTRATION_TIMEOUTS_ENABLED: false,
  ORCHESTRATION_RETRIES_ENABLED: false,
  ORCHESTRATION_SCHEDULER_ENABLED: false,
  ORCHESTRATION_MANUAL_INTERVENTION_ENABLED: false,
  ORCHESTRATION_INSPECTOR_ENABLED: false,
  ORCHESTRATION_VISUALIZATION_ENABLED: false,
  PROTECTED_INTERVIEW_ENABLED: false,
  VIDEO_ROOM_PROVIDER_ENABLED: false,
  INTERVIEW_TOKEN_ENABLED: false,
  INTERVIEW_LIFECYCLE_ENABLED: false,
  PROTECTION_ENGINE_ENABLED: false,
  REDACTION_ENGINE_ENABLED: false,
  PROTECTED_COPY_ENABLED: false,
  AUTO_MASKING_ENABLED: false,
  PROTECTION_EVENTS_ENABLED: false,
  PROTECTION_AUDIT_ENABLED: false,
  PROTECTION_TIMELINE_ENABLED: false,
};

function readBooleanFlag(name: Phase10FeatureFlagName): boolean {
  const value = process.env[name]?.trim().toLowerCase();
  if (!value) return DEFAULT_PHASE10_FLAGS[name];
  return ["1", "true", "yes", "on", "enabled"].includes(value);
}

export function getPhase10FeatureFlags(): Phase10FeatureFlags {
  return {
    PRIME_SHIELD_ENABLED: readBooleanFlag("PRIME_SHIELD_ENABLED"),
    PROTECTED_INTERVIEWS_ENABLED: readBooleanFlag("PROTECTED_INTERVIEWS_ENABLED"),
    SHIELD_ATTACHMENT_SCANNING_ENABLED: readBooleanFlag("SHIELD_ATTACHMENT_SCANNING_ENABLED"),
    SHIELD_PROGRESSIVE_ENFORCEMENT_ENABLED: readBooleanFlag("SHIELD_PROGRESSIVE_ENFORCEMENT_ENABLED"),
    RECRUITMENT_TIMELINE_ENABLED: readBooleanFlag("RECRUITMENT_TIMELINE_ENABLED"),
    CIRCUMVENTION_RISK_ENABLED: readBooleanFlag("CIRCUMVENTION_RISK_ENABLED"),
    AI_RECRUITER_ASSISTANT_ENABLED: readBooleanFlag("AI_RECRUITER_ASSISTANT_ENABLED"),
    AI_CANDIDATE_COACH_ENABLED: readBooleanFlag("AI_CANDIDATE_COACH_ENABLED"),
    VIDEO_ROOMS_ENABLED: readBooleanFlag("VIDEO_ROOMS_ENABLED"),
    SERVICE_FEE_GATE_ENABLED: readBooleanFlag("SERVICE_FEE_GATE_ENABLED"),
    GOVERNANCE_CENTER_ENABLED: readBooleanFlag("GOVERNANCE_CENTER_ENABLED"),
    ENTERPRISE_SLA_ENABLED: readBooleanFlag("ENTERPRISE_SLA_ENABLED"),
    TENANT_ABSTRACTION_ENABLED: readBooleanFlag("TENANT_ABSTRACTION_ENABLED"),
    SHIELD_INFRA_FOUNDATION_ENABLED: readBooleanFlag("SHIELD_INFRA_FOUNDATION_ENABLED"),
    SHIELD_INTEGRITY_MONITOR_ENABLED: readBooleanFlag("SHIELD_INTEGRITY_MONITOR_ENABLED"),
    SHIELD_EVENT_REPLAY_ENABLED: readBooleanFlag("SHIELD_EVENT_REPLAY_ENABLED"),
    SHIELD_EVIDENCE_VERSIONING_ENABLED: readBooleanFlag("SHIELD_EVIDENCE_VERSIONING_ENABLED"),
    SHIELD_MIGRATION_COMPATIBILITY_ENABLED: readBooleanFlag("SHIELD_MIGRATION_COMPATIBILITY_ENABLED"),
    WORKFLOW_KERNEL_ENABLED: readBooleanFlag("WORKFLOW_KERNEL_ENABLED"),
    WORKFLOW_COMMANDS_ENABLED: readBooleanFlag("WORKFLOW_COMMANDS_ENABLED"),
    WORKFLOW_QUERIES_ENABLED: readBooleanFlag("WORKFLOW_QUERIES_ENABLED"),
    WORKFLOW_IDEMPOTENCY_ENABLED: readBooleanFlag("WORKFLOW_IDEMPOTENCY_ENABLED"),
    WORKFLOW_LOCKING_ENABLED: readBooleanFlag("WORKFLOW_LOCKING_ENABLED"),
    WORKFLOW_OPTIMISTIC_LOCKING_ENABLED: readBooleanFlag("WORKFLOW_OPTIMISTIC_LOCKING_ENABLED"),
    WORKFLOW_COMPENSATION_ENABLED: readBooleanFlag("WORKFLOW_COMPENSATION_ENABLED"),
    WORKFLOW_EVENT_REPLAY_ENABLED: readBooleanFlag("WORKFLOW_EVENT_REPLAY_ENABLED"),
    RECRUITMENT_ORCHESTRATOR_ENABLED: readBooleanFlag("RECRUITMENT_ORCHESTRATOR_ENABLED"),
    ORCHESTRATION_SAGAS_ENABLED: readBooleanFlag("ORCHESTRATION_SAGAS_ENABLED"),
    ORCHESTRATION_GRAPHS_ENABLED: readBooleanFlag("ORCHESTRATION_GRAPHS_ENABLED"),
    ORCHESTRATION_SNAPSHOTS_ENABLED: readBooleanFlag("ORCHESTRATION_SNAPSHOTS_ENABLED"),
    ORCHESTRATION_RECOVERY_ENABLED: readBooleanFlag("ORCHESTRATION_RECOVERY_ENABLED"),
    ORCHESTRATION_TIMEOUTS_ENABLED: readBooleanFlag("ORCHESTRATION_TIMEOUTS_ENABLED"),
    ORCHESTRATION_RETRIES_ENABLED: readBooleanFlag("ORCHESTRATION_RETRIES_ENABLED"),
    ORCHESTRATION_SCHEDULER_ENABLED: readBooleanFlag("ORCHESTRATION_SCHEDULER_ENABLED"),
    ORCHESTRATION_MANUAL_INTERVENTION_ENABLED: readBooleanFlag("ORCHESTRATION_MANUAL_INTERVENTION_ENABLED"),
    ORCHESTRATION_INSPECTOR_ENABLED: readBooleanFlag("ORCHESTRATION_INSPECTOR_ENABLED"),
    ORCHESTRATION_VISUALIZATION_ENABLED: readBooleanFlag("ORCHESTRATION_VISUALIZATION_ENABLED"),
    PROTECTED_INTERVIEW_ENABLED: readBooleanFlag("PROTECTED_INTERVIEW_ENABLED"),
    VIDEO_ROOM_PROVIDER_ENABLED: readBooleanFlag("VIDEO_ROOM_PROVIDER_ENABLED"),
    INTERVIEW_TOKEN_ENABLED: readBooleanFlag("INTERVIEW_TOKEN_ENABLED"),
    INTERVIEW_LIFECYCLE_ENABLED: readBooleanFlag("INTERVIEW_LIFECYCLE_ENABLED"),
    PROTECTION_ENGINE_ENABLED: readBooleanFlag("PROTECTION_ENGINE_ENABLED"),
    REDACTION_ENGINE_ENABLED: readBooleanFlag("REDACTION_ENGINE_ENABLED"),
    PROTECTED_COPY_ENABLED: readBooleanFlag("PROTECTED_COPY_ENABLED"),
    AUTO_MASKING_ENABLED: readBooleanFlag("AUTO_MASKING_ENABLED"),
    PROTECTION_EVENTS_ENABLED: readBooleanFlag("PROTECTION_EVENTS_ENABLED"),
    PROTECTION_AUDIT_ENABLED: readBooleanFlag("PROTECTION_AUDIT_ENABLED"),
    PROTECTION_TIMELINE_ENABLED: readBooleanFlag("PROTECTION_TIMELINE_ENABLED"),
  };
}

export function isPhase10FeatureEnabled(name: Phase10FeatureFlagName): boolean {
  return getPhase10FeatureFlags()[name];
}

export function getPhase10FeatureFlagSnapshot(): Phase10FeatureFlagSnapshot {
  return {
    flags: getPhase10FeatureFlags(),
    source: "environment",
    evaluatedAt: new Date().toISOString(),
  };
}

export type { Phase10FeatureFlagSnapshot, Phase10FeatureFlags, Phase10FeatureFlagName } from "./types.ts";
