export type Phase10FeatureFlagName =
  | "PRIME_SHIELD_ENABLED"
  | "PROTECTED_INTERVIEWS_ENABLED"
  | "SHIELD_ATTACHMENT_SCANNING_ENABLED"
  | "SHIELD_PROGRESSIVE_ENFORCEMENT_ENABLED"
  | "RECRUITMENT_TIMELINE_ENABLED"
  | "CIRCUMVENTION_RISK_ENABLED"
  | "AI_RECRUITER_ASSISTANT_ENABLED"
  | "AI_CANDIDATE_COACH_ENABLED"
  | "VIDEO_ROOMS_ENABLED"
  | "SERVICE_FEE_GATE_ENABLED"
  | "GOVERNANCE_CENTER_ENABLED"
  | "ENTERPRISE_SLA_ENABLED"
  | "TENANT_ABSTRACTION_ENABLED"
  | "SHIELD_INFRA_FOUNDATION_ENABLED"
  | "SHIELD_INTEGRITY_MONITOR_ENABLED"
  | "SHIELD_EVENT_REPLAY_ENABLED"
  | "SHIELD_EVIDENCE_VERSIONING_ENABLED"
  | "SHIELD_MIGRATION_COMPATIBILITY_ENABLED"
  | "WORKFLOW_KERNEL_ENABLED"
  | "WORKFLOW_COMMANDS_ENABLED"
  | "WORKFLOW_QUERIES_ENABLED"
  | "WORKFLOW_IDEMPOTENCY_ENABLED"
  | "WORKFLOW_LOCKING_ENABLED"
  | "WORKFLOW_OPTIMISTIC_LOCKING_ENABLED"
  | "WORKFLOW_COMPENSATION_ENABLED"
  | "WORKFLOW_EVENT_REPLAY_ENABLED";

export interface Phase10FeatureFlags {
  PRIME_SHIELD_ENABLED: boolean;
  PROTECTED_INTERVIEWS_ENABLED: boolean;
  SHIELD_ATTACHMENT_SCANNING_ENABLED: boolean;
  SHIELD_PROGRESSIVE_ENFORCEMENT_ENABLED: boolean;
  RECRUITMENT_TIMELINE_ENABLED: boolean;
  CIRCUMVENTION_RISK_ENABLED: boolean;
  AI_RECRUITER_ASSISTANT_ENABLED: boolean;
  AI_CANDIDATE_COACH_ENABLED: boolean;
  VIDEO_ROOMS_ENABLED: boolean;
  SERVICE_FEE_GATE_ENABLED: boolean;
  GOVERNANCE_CENTER_ENABLED: boolean;
  ENTERPRISE_SLA_ENABLED: boolean;
  TENANT_ABSTRACTION_ENABLED: boolean;
  SHIELD_INFRA_FOUNDATION_ENABLED: boolean;
  SHIELD_INTEGRITY_MONITOR_ENABLED: boolean;
  SHIELD_EVENT_REPLAY_ENABLED: boolean;
  SHIELD_EVIDENCE_VERSIONING_ENABLED: boolean;
  SHIELD_MIGRATION_COMPATIBILITY_ENABLED: boolean;
  WORKFLOW_KERNEL_ENABLED: boolean;
  WORKFLOW_COMMANDS_ENABLED: boolean;
  WORKFLOW_QUERIES_ENABLED: boolean;
  WORKFLOW_IDEMPOTENCY_ENABLED: boolean;
  WORKFLOW_LOCKING_ENABLED: boolean;
  WORKFLOW_OPTIMISTIC_LOCKING_ENABLED: boolean;
  WORKFLOW_COMPENSATION_ENABLED: boolean;
  WORKFLOW_EVENT_REPLAY_ENABLED: boolean;
}

export interface Phase10FeatureFlagSnapshot {
  flags: Phase10FeatureFlags;
  source: "environment";
  evaluatedAt: string;
}
